# Generated by Django 5.0.6 on 2024-07-27 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(db_index=True, max_length=36)),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('dob', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(db_index=True, max_length=36)),
                ('is_sent', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_items', to='mailing.mailevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='mailing.user')),
            ],
        ),
        migrations.AddField(
            model_name='mailevent',
            name='receivers',
            field=models.ManyToManyField(null=True, related_name='received_mail_events', to='mailing.user'),
        ),
        migrations.AddField(
            model_name='mailevent',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_mail_events', to='mailing.user'),
        ),
    ]
