# Generated by Django 5.0.6 on 2024-10-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_rawevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawevent',
            old_name='paylaod',
            new_name='payload',
        ),
    ]
