# Generated by Django 5.0.6 on 2024-10-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_rename_paylaod_rawevent_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawevent',
            name='chain_id',
            field=models.CharField(db_index=True, default=1, max_length=36),
            preserve_default=False,
        ),
    ]
